variable "frontend_subnets"{}
variable "backend_subnets"{}
variable "db_subnets"{}
variable "vpc_id"{}
variable "env"{}
variable "availability_zones"{}
variable "instance_type"{}
variable "default_cidr_block"{}
variable "default_vpc_id"{}